[package]
name = "ember"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader_api = "0.11.15"
uart_16550 = "0.3"
x86_64 = "0.14"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
spin = "0.9"
bootloader = "0.11.15"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
